### ISSUE TITLE
no PHP 7.1 support?

### ISSUE THREAD

**Issue by huggenknubbel** [gilbitron/Baun#22]
Hello, 
i tried to install BaunCMS on archlinux with Apache2 and PHP7.1.6
after "composer install" which run without an error, Baun doesn't work.

here is my error.log

`[Thu Mar 09 04:59:07.719293 2017] [php7:error] [pid 1878] [client 79.245.161.243:61363] PHP Fatal error:  Uncaught Error: Call to undefined function Baun\\Providers\\iconv() in /usr/share/webapps/www/Baun/vendor/bauncms/framework/src/Providers/Theme.php:86\nStack trace:\n#0 /usr/share/webapps/www/Baun/vendor/bauncms/framework/src/Providers/Theme.php(69): Baun\\Providers\\Theme->slugify('Home')\n#1 /usr/share/webapps/www/Baun/vendor/bauncms/framework/src/Providers/Theme.php(48): Baun\\Providers\\Theme->navToHTML(Array)\n#2 /usr/share/webapps/www/Baun/vendor/twig/twig/lib/Twig/Environment.php(462) : eval()'d code(70): Baun\\Providers\\Theme->custom_baun_nav()\n#3 /usr/share/webapps/www/Baun/vendor/twig/twig/lib/Twig/Template.php(432): __TwigTemplate_35c8b5a9653dfd03de3b33ffb4c095f123e7865e533b8ec9cf70f188cb842d76->doDisplay(Array, Array)\n#4 /usr/share/webapps/www/Baun/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array)\n#5 /usr/share/webapps/www/Baun/vendor/twig/twig/lib/Twig/Environment.php(462) : eval()'d code(24): Twig_Template->display(Array, Array)\n#6 /usr/share/webapps/www/Bau in /usr/share/webapps/www/Baun/vendor/bauncms/framework/src/Providers/Theme.php on line 86`

**Comment by marksouthard** [comment]
Baun should work on php7.1. Your setup must have iconv disabled. Can you check if iconv is enabled in php?

**Comment by ghost** [comment]
I can also confirm that Baun CMS is running under PHP 7.1, Plesk, Subdomain on Rootserver 👍
