### ISSUE TITLE
How can you offer your own Downloads on a Page in Baun CMS?

### ISSUE THREAD

**Issue by ghost** [gilbitron/Baun#23]
Hello Developers,

I would like to offer on a page in the navigation downloads. How do I upload and download a zip file?

I have created the `/assets` directory in the root directory, but this page does not exist.

Thanks in advance.

**Comment by marksouthard** [comment]
You'll want to create a new page for where your downloads will be listed. Right now, the .zip files would need to be uploaded to the `/assets` directory that is in the public folder via FTP or similar. In the page, you'll link to the files in the asset folder using their exact URL. You should be able to use something like: `base_url() . /assets/zips/XXXX.zip`

**Comment by ghost** [comment]
Thanks for the thought and I could realize it, but had to take the whole URL instead of "base url". Otherwise it would not work.

But now good to know how to do that.
